### ISSUE TITLE
Would ♥ to see a screenshot...

### ISSUE THREAD

**Issue by PySimpleGUI** [huntbrooks85/WRAP#9]
I see you've written quite a bit of GUI code!  I would love to see what it looks like.  Do you have a screenshot that you can drop into your readme?  I'm sure other visitors would be interested as well.  It's not very common for Python projects to have a GUI.

**Comment by huntbrooks85** [comment]
We are delighted to see interest!
<img width="542" alt="WRAP_Screenshot" src="https://github.com/huntbrooks85/WRAP/assets/82741785/09d44ded-949c-4ede-8fbc-8c69e67a5c56">
